### ISSUE TITLE
Tests fail due to testonly attribute

### ISSUE THREAD

**Issue by katre** [bazelbuild/rules_appengine#34]
Error:
```
ERROR: /home/ci/workspace/rules_appengine/BAZEL_VERSION/HEAD/PLATFORM_NAME/linux-x86_64/test/BUILD:3:1: unexpected keyword 'testonly' in call to appengine_war(name, jars, data, data_path).
```

See logs at http://ci.bazel.io/view/Dashboard/job/rules_appengine/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/lastFailedBuild/console

**Comment by kchodorow** [comment]
Fixed by d298c71f56c67d47f885379ca2622972c2757d8b.
