### ISSUE TITLE
App Engine deployment should use "gcloud" cli rather than "appcfg.py" (or have a way to use "gcloud")

### ISSUE THREAD

**Issue by michaelsafyan** [bazelbuild/rules_appengine#64]
# Steps to reproduce:
 
   1. Create a `py_appengine_binary` target
   2. Build the `.deploy` target
   3. Run the `.deploy` script

# Observed:

This command runs `appcfg.py`

# Expected

This should run `gcloud app deploy`

# Rationale

The gcloud cli is the more modern approach to deploying to App Engine. Additionally, `gcloud app deploy` can pick up the project from a prior invocation of `gcloud config set project` without having to specific it in the invocation explicitly (as is the case with `appcfg.py`). Likewise, `gcloud app deploy` is capable of auto-assigning a version number (based on the date), whereas `appcfg.py` requires an explicit `-V` parameter with the version specification.

**Comment by fejta** [comment]
Probability of this getting addressed?

**Comment by pmbethe09** [comment]
If you are someone else does the work, I can review it, but I don't have the cycles right now to do it myself.
