### ISSUE TITLE
Latest release (0.0.7) does not include java_appengine.bzl

### ISSUE THREAD

**Issue by andreihalici** [bazelbuild/rules_appengine#77]
Hello, 

The tag specified in the README file (0.0.7) does not include the java_appengine.bzl file, please generate a new release that includes the required files. 

Workaround (specify the commit instead of the tag):
`git_repository(
    name = "io_bazel_rules_appengine",
    remote = "https://github.com/bazelbuild/rules_appengine.git",
    # Check https://github.com/bazelbuild/rules_appengine/releases for the latest version.
    #tag = "0.0.7",
    commit = "44caf2de649bb37a41408a821d04833450fa89a3",
)`

**Comment by pmbethe09** [comment]
https://github.com/bazelbuild/rules_appengine/releases/tag/0.0.8
